# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 172)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.email = QtWidgets.QLineEdit(self.splitter)
        self.email.setObjectName("email")
        self.combo_mail = QtWidgets.QComboBox(self.splitter)
        self.combo_mail.setObjectName("combo_mail")
        self.combo_mail.addItem("")
        self.combo_mail.addItem("")
        self.combo_mail.addItem("")
        self.verticalLayout.addWidget(self.splitter)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.passwd = QtWidgets.QLineEdit(self.centralwidget)
        self.passwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwd.setObjectName("passwd")
        self.verticalLayout.addWidget(self.passwd)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.btn_login = QtWidgets.QPushButton(self.splitter_2)
        self.btn_login.setObjectName("btn_login")
        self.btn_reg = QtWidgets.QPushButton(self.splitter_2)
        self.btn_reg.setObjectName("btn_reg")
        self.verticalLayout.addWidget(self.splitter_2)
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        self.label_info.setText("")
        self.label_info.setObjectName("label_info")
        self.verticalLayout.addWidget(self.label_info)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Вход"))
        self.label.setText(_translate("MainWindow", "Почта"))
        self.combo_mail.setItemText(0, _translate("MainWindow", "@gmail.com"))
        self.combo_mail.setItemText(1, _translate("MainWindow", "@mail.ru"))
        self.combo_mail.setItemText(2, _translate("MainWindow", "@yandex.ru"))
        self.label_2.setText(_translate("MainWindow", "Пароль"))
        self.btn_login.setText(_translate("MainWindow", "Вход"))
        self.btn_reg.setText(_translate("MainWindow", "Регистрация"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
